--- BigQuery Database Development
--- Creating the Primary Table for Neighborhood data

CREATE OR REPLACE TABLE `nyc_analysis.ref_neighborhoods` (
    neighborhood_id INT64,
    name STRING,
    borough_id INT64
    -- FOREIGN KEY (borough_id) REFERENCES boroughs(borough_id)
);

-- Adding neighborhood table data
-- Bronx neighborhoods (Borough ID: 4)
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (1, 'Baychester', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (2, 'Bedford Park', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (3, 'Belmont', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (4, 'Bronxwood', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (5, 'Castle Hill', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (6, 'City Island', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (7, 'Co-op City', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (8, 'Concourse', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (9, 'Country Club', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (10, 'Crotona Park East', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (11, 'East Tremont', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (12, 'Eastchester', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (13, 'Edenwald', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (14, 'Fordham', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (15, 'Highbridge', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (16, 'Hunts Point', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (17, 'Kingsbridge', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (18, 'Laconia', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (19, 'Longwood', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (20, 'Melrose', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (21, 'Morris Heights', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (22, 'Morris Park', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (23, 'Morrisania', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (24, 'Mott Haven', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (25, 'Norwood', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (26, 'Parkchester', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (27, 'Pelham Bay', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (28, 'Pelham Gardens', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (29, 'Pelham Parkway', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (30, 'Port Morris', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (31, 'Riverdale', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (32, 'Schuylerville', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (33, 'Soundview', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (34, 'Throgs Neck', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (35, 'Tremont', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (36, 'University Heights', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (37, 'Van Nest', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (38, 'Wakefield', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (39, 'Westchester Village', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (40, 'Williamsbridge', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (41, 'Woodlawn', 4);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (42, 'Woodstock', 4);
-- Brooklyn Neighborhoods (Borough ID: 2)
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (43, 'Bath Beach', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (44, 'Bay Ridge', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (45, 'Bedford-Stuyvesant', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (46, 'Bensonhurst', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (47, 'Bergen Beach', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (48, 'Boerum Hill', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (49, 'Borough Park', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (50, 'Brighton Beach', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (51, 'Brooklyn Heights', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (52, 'Brownsville', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (53, 'Bushwick', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (54, 'Canarsie', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (55, 'Carroll Gardens', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (56, 'Clinton Hill', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (57, 'Cobble Hill', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (58, 'Columbia St Waterfront District', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (59, 'Coney Island', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (60, 'Crown Heights', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (61, 'Ditmas Park', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (62, 'Downtown Brooklyn', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (63, 'DUMBO', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (64, 'Dyker Heights', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (65, 'East Flatbush', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (66, 'East New York', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (67, 'Flatbush', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (68, 'Flatlands', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (69, 'Fort Greene', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (70, 'Gerritsen Beach', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (71, 'Gowanus', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (72, 'Gravesend', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (73, 'Greenpoint', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (74, 'Greenwood', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (75, 'Kensington', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (76, 'Manhattan Beach', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (77, 'Marine Park', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (78, 'Midwood', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (79, 'Mill Basin', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (80, 'Ocean Parkway', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (81, 'Old Mill Basin', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (82, 'Park Slope', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (83, 'Prospect Heights', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (84, 'Prospect Lefferts Gardens', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (85, 'Prospect Park South', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (86, 'Red Hook', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (87, 'Seagate', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (88, 'Sheepshead Bay', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (89, 'Sunset Park', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (90, 'Williamsburg', 2);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (91, 'Windsor Terrace', 2);
-- Manhattan Neighborhoods (Borough ID: 1)
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (92, 'Battery Park City', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (93, 'Central Harlem', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (94, 'Central Park South', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (95, 'Chelsea', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (96, 'Chinatown', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (97, 'Civic Center', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (98, 'East Harlem', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (99, 'East Village', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (100, 'Financial District', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (101, 'Flatiron', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (102, 'Gramercy Park', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (103, 'Greenwich Village', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (104, 'Hamilton Heights', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (105, "Hell''s Kitchen", 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (106, 'Inwood', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (107, 'Little Italy', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (108, 'Lower East Side', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (109, 'Marble Hill', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (110, 'Midtown', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (111, 'Midtown East', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (112, 'Midtown South', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (113, 'Midtown West', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (114, 'Morningside Heights', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (115, 'Nolita', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (116, 'Roosevelt Island', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (117, 'Soho', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (118, 'Stuyvesant Town/PCV', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (119, 'Tribeca', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (120, 'Upper East Side', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (121, 'Upper West Side', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (122, 'Washington Heights', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (123, 'West Harlem', 1);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (124, 'West Village', 1);
-- Queens Neighborhoods (Borough ID: 3)
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (125, 'Astoria', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (126, 'Auburndale', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (127, 'Bayside', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (128, 'Bellerose', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (129, 'Briarwood', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (130, 'Brookville', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (131, 'Cambria Heights', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (132, 'Clearview', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (133, 'College Point', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (134, 'Corona', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (135, 'Douglaston', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (136, 'East Elmhurst', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (137, 'Elmhurst', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (138, 'Floral Park', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (139, 'Flushing', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (140, 'Forest Hills', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (141, 'Fresh Meadows', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (142, 'Glen Oaks', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (143, 'Glendale', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (144, 'Hillcrest', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (145, 'Hollis', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (146, 'Howard Beach', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (147, 'Jackson Heights', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (148, 'Jamaica', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (149, 'Jamaica Estates', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (150, 'Jamaica Hills', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (151, 'Kew Gardens', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (152, 'Kew Gardens Hills', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (153, 'Laurelton', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (154, 'Little Neck', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (155, 'Long Island City', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (156, 'Maspeth', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (157, 'Middle Village', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (158, 'New Hyde Park', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (159, 'North Corona', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (160, 'Oakland Gardens', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (161, 'Ozone Park', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (162, 'Pomonok', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (163, 'Queens Village', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (164, 'Rego Park', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (165, 'Richmond Hill', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (166, 'Ridgewood', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (167, 'Rockaway All', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (168, 'Rosedale', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (169, 'South Jamaica', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (170, 'South Ozone Park', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (171, 'South Richmond Hill', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (172, 'Springfield Gardens', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (173, 'St. Albans', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (174, 'Sunnyside', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (175, 'Utopia', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (176, 'Whitestone', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (177, 'Woodhaven', 3);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (178, 'Woodside', 3);
-- Staten Island Neighborhoods (Borough ID: 5)
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (179, 'North Shore', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (180, 'Port Richmond', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (181, 'Stapleton', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (182, 'Mariners Harbor', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (183, 'Mid-Island', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (184, 'New Springville', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (185, 'South Beach', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (186, 'South Shore', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (187, 'Tottenville', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (188, 'Great Kills', 5);
INSERT INTO nyc_analysis.ref_neighborhoods (neighborhood_id, name, borough_id) VALUES (189, 'Annadale', 5);