name: Update and Normalize Rent Tables, and Calculate YoY Change Percent Tables in BQ 

on:
  push:
    branches:
      - main
  
  # Allow manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Authenticate Google Cloud Connection
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: rent-affordability
          install_components: bq

      - name: Verify authentication
        run: gcloud auth list

      - name: Create reference tables for foreign key connections
        run: |
            set -e
            bq query \
                --project_id=rent_affordability \
                --use_legacy_sql=false \
                < BigQuery/bigquery_init_reference_tables.sql 

      - name: Execute normalization and analysis Script
        run: |
            set -e
            bq query \
                --project_id=rent_affordability \
                --use_legacy_sql=false \
                < BigQuery/SQL/normalize_analyze_median_rent.sql